import {
  ArrowLeft,
  ArrowRight,
  BadgeHelp,
  BarChart3,
  Bell,
  BellOff,
  Boxes,
  Check,
  ChefHat,
  Clock3,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Hash,
  KeyRound,
  LayoutDashboard,
  MapPin,
  Menu,
  MessageSquareMore,
  Package,
  Phone,
  Plus,
  QrCode,
  ReceiptText,
  RefreshCw,
  Route,
  ScanLine,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Store,
  Tag,
  Truck,
  UserRound,
  UsersRound,
  WalletCards,
  X,
} from 'lucide-react'

const icons = {
  arrow: ArrowRight,
  back: ArrowLeft,
  bell: Bell,
  bellOff: BellOff,
  box: Package,
  chef: ChefHat,
  check: Check,
  chart: BarChart3,
  clock: Clock3,
  close: X,
  copy: Copy,
  customers: UsersRound,
  dashboard: LayoutDashboard,
  download: Download,
  external: ExternalLink,
  hash: Hash,
  help: BadgeHelp,
  key: KeyRound,
  menu: Menu,
  orders: ShoppingBag,
  phone: Phone,
  pin: MapPin,
  plus: Plus,
  qr: QrCode,
  receipt: ReceiptText,
  route: Route,
  scan: ScanLine,
  send: Send,
  refresh: RefreshCw,
  settings: Settings,
  shield: ShieldCheck,
  spark: Sparkles,
  store: Store,
  tag: Tag,
  truck: Truck,
  user: UserRound,
  wallet: WalletCards,
  message: MessageSquareMore,
  card: CreditCard,
}

export function Icon({ name, className = 'h-[22px] w-[22px]' }) {
  if (name === 'G') {
    return <span className="google-letter">G</span>
  }

  const LucideIcon = icons[name] || Boxes
  return <LucideIcon className={className} aria-hidden="true" strokeWidth={2.35} />
}
